apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "..fullname" . }}-env
  labels:
     {{- include "..labels" . | nindent 4 }}
data:
  SERVICE_PORT: "8080"
  ACCOUNT_API_ENDPOINT: {{ .Values.appEnv.endPoint }}
  SUBSCRIPTION_KEY: {{ .Values.appEnv.subscriptionKey }}


