apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "..fullname" . }}-env
  labels:
     {{- include "..labels" . | nindent 4 }}
data:
  SERVICE_PORT: {{ .Values.appEnv.servicePort}}
  ACCOUNT_API_ENDPOINT: {{ .Values.appEnv.endPoint }}


